version: '2'
services:
    daspanel-alpine-base:
        build:
            context: .
            dockerfile: Dockerfile
        image: daspanel/alpine-base-edge
        volumes:
            - ./src:/opt/daspanel/data
        networks:
            - frontend
            - backend
        environment:
            - LOCAL_USER_ID=1000
        env_file:
            - daspanel.env
            - smtp.env

volumes:
    daspanel-data:
        external:
            name: daspanel-data

networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


