#!/usr/bin/with-contenv sh

USER_ID=${LOCAL_USER_ID:-1000}
echo "Starting with UID : $USER_ID"
addgroup -g $USER_ID daspanel
adduser -s /bin/false -D -h /home/daspanel -u $USER_ID -G daspanel daspanel

# Master admin email must be informed
if [ -z "$DASPANEL_MASTER_EMAIL" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_MASTER_EMAIL to a valid email"
    echo "***"
    exit 1
fi

# unless this has already been defined, set
if [ -z "$DASPANEL_MASTER_PASSWORD" ]; then
    MASTER_PASSWORD=`date +%s | sha256sum | base64 | head -c 16 ; echo`
    echo "set DASPANEL master password to random password: $MASTER_PASSWORD"
    printf $MASTER_PASSWORD > /var/run/s6/container_environment/DASPANEL_MASTER_PASSWORD
    export DASPANEL_MASTER_PASSWORD="$MASTER_PASSWORD"
fi

# unless this has already been defined, set
if [ -z "$DASPANEL_GUUID" ]; then
    wget -q -O- https://9jzojg54n7.execute-api.us-east-1.amazonaws.com/v1/uuid --no-check-certificate > /tmp/dasuuid
    DASPANEL_GUUID=`cat /tmp/dasuuid | /usr/bin/jq -r '.uuid'`
    echo "DASPANEL GUUID = $DASPANEL_GUUID"
    printf $DASPANEL_GUUID > /var/run/s6/container_environment/DASPANEL_GUUID
   
fi

if [ ! -d "/opt/daspanel/data/$DASPANEL_GUUID" ]; then
	mkdir -p "/opt/daspanel/data/$DASPANEL_GUUID"
fi

if [ ! -d "/opt/daspanel/log/$DASPANEL_GUUID" ]; then
	mkdir -p "/opt/daspanel/log/$DASPANEL_GUUID"
fi

# secure daspanel
chown -R daspanel:daspanel /opt/daspanel/data
chown -R daspanel:daspanel /opt/daspanel/log

