#!/usr/bin/with-contenv sh

if [ -z "$DASPANEL_MAIL_HUB" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_MAIL_HUB"
    echo "***"
    exit 1
fi

if [ -z "$DASPANEL_MAIL_SERVER" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_MAIL_SERVER"
    echo "***"
    exit 1
fi

if [ -z "$DASPANEL_MAIL_USER" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_MAIL_USER"
    echo "***"
    exit 1
fi

if [ -z "$DASPANEL_MAIL_PWD" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_MAIL_PWD"
    echo "***"
    exit 1
fi

# Configure ssmtp
/usr/bin/templater -d -p daspanel \
  -o /etc/ssmtp/ssmtp.conf \
  /opt/daspanel/conf-templates/etc/ssmtp/gmail-ssmtp.conf.tmpl

/usr/bin/templater -d -p daspanel \
  -o /etc/ssmtp/revaliases \
  /opt/daspanel/conf-templates/etc/ssmtp/gmail-revaliases.tmpl

# secure ssmtp - https://wiki.archlinux.org/index.php/SSMTP
addgroup ssmtp
chown :ssmtp /etc/ssmtp/ssmtp.conf
chown :ssmtp /usr/sbin/ssmtp
chmod g+s /usr/sbin/ssmtp

## Send email with instance info
#{ 
#    echo "To: $DASPANEL_MASTER_EMAIL"; 
#    echo "From: $DASPANEL_MAIL_USER"; 
#    echo "Subject: DASPANEL instance $DASPANEL_GUUID is running"; 
#    echo ""; 
#    echo "Teste enviado inside daspanel docker alpine base"; 
#} | ssmtp -vvv $DASPANEL_MASTER_EMAIL

